### ISSUE TITLE
[Bug report] Crash lorsque le message d'un giveaway est supprimé et qu'il termine

### ISSUE THREAD

**Issue by GoudronViande24** [Artivain/artibot#14]
**Description du bug**
Lorsque le message d'un giveaway est supprimé par un utilisateur et que le giveaway termine, il essaie de faire des actions sur le message mais crash puisqu'il n'existe plus. Voici le message d'erreur:
```js
/home/container/artibot/node_modules/discord.js/src/rest/RequestHandler.js:349
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown Message
    at RequestHandler.execute (/home/container/artibot/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/container/artibot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async ReactionUserManager.fetch (/home/container/artibot/node_modules/discord.js/src/managers/ReactionUserManager.js:43:18)
    at async Giveaway.roll (/home/container/artibot/node_modules/discord-giveaways/src/Giveaway.js:440:30)
    at async /home/container/artibot/node_modules/discord-giveaways/src/Giveaway.js:554:29 {
  method: 'get',
  path: '/channels/829137216105742337/messages/930610911893401630/reactions/%F0%9F%8E%89?limit=100',
  code: 10008,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}
```

**Pour reproduire**
Étapes pour reproduire le bug:
1. Créer un giveaway et mettre une durée de genre 1 minute
2. Supprimer le message
3. Le bot va crash car ça fait une unhandled exception dans 1 minute

**Comportement attendu**
Au minimum ne pas crash. Ce qui serait bien aussi c'est si ça envoi un message au host du giveaway pour lui dire.

**Captures d'écran**
![image](https://user-images.githubusercontent.com/42936037/149040762-0e2de924-509a-4a0f-83a6-d8430176fc28.png)

**Informations systèmes**
 - Version de Node.js: 16.6.1
 - Hébergement du bot: Artivain Hosting

**Comment by GoudronViande24** [comment]
Fixed in 148ae13
